#!/bin/sh

echo >> /mnt/us/scripts/logs.txt

date >> /mnt/us/scripts/logs.txt
# turn off the screen
cat /sys/devices/system/fl_tps6116x/fl_tps6116x0/fl_intensity >> /mnt/us/scripts/logs.txt
echo turn off the screen >> /mnt/us/scripts/logs.txt
echo -n 0 > /sys/devices/system/fl_tps6116x/fl_tps6116x0/fl_intensity
cat /sys/devices/system/fl_tps6116x/fl_tps6116x0/fl_intensity >> /mnt/us/scripts/logs.txt

date >> /mnt/us/scripts/logs.txt
echo Kindle awakes >> /mnt/us/scripts/logs.txt

while true; do

    echo >> /mnt/us/scripts/logs.txt

    date >> /mnt/us/scripts/logs.txt
    echo Battery Infos : >> /mnt/us/scripts/logs.txt
    gasgauge-info -c >> /mnt/us/scripts/logs.txt
    gasgauge-info -v >> /mnt/us/scripts/logs.txt
    gasgauge-info -m >> /mnt/us/scripts/logs.txt
    gasgauge-info -m >> /mnt/us/scripts/logs.txt

    date >> /mnt/us/scripts/logs.txt
    # increase processor frequency
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor >> /mnt/us/scripts/logs.txt
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq >> /mnt/us/scripts/logs.txt
    echo increase processor frequency >> /mnt/us/scripts/logs.txt
    echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor >> /mnt/us/scripts/logs.txt
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq >> /mnt/us/scripts/logs.txt

    date >> /mnt/us/scripts/logs.txt
    # enable WiFi
    echo enable WiFi : >> /mnt/us/scripts/logs.txt
    lipc-set-prop com.lab126.cmd wirelessEnable 1
    lipc-get-prop com.lab126.cmd wirelessEnable >> /mnt/us/scripts/logs.txt
    # delay needed to connect to the WiFi AP
    sleep 10

    date >> /mnt/us/scripts/logs.txt
    # calendar update
    echo calendar update >> /mnt/us/scripts/logs.txt
    /mnt/us/extensions/WebLaunch/bin/start.sh &

    date >> /mnt/us/scripts/logs.txt
    # delay nedeed to do the update
    sleep 10

    date >> /mnt/us/scripts/logs.txt
    # disable WiFi
    echo disable WiFi : >> /mnt/us/scripts/logs.txt
    lipc-set-prop com.lab126.cmd wirelessEnable 0
    lipc-get-prop com.lab126.cmd wirelessEnable >> /mnt/us/scripts/logs.txt

    date >> /mnt/us/scripts/logs.txt
    # lowered processor frequency
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor >> /mnt/us/scripts/logs.txt
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq >> /mnt/us/scripts/logs.txt
    echo lowered processor frequency >> /mnt/us/scripts/logs.txt
    echo powersave > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor >> /mnt/us/scripts/logs.txt
    cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq >> /mnt/us/scripts/logs.txt

    date >> /mnt/us/scripts/logs.txt
    # sleep during 1 hour
    echo sleep during 1 hour >> /mnt/us/scripts/logs.txt
    sleep 3600

done