#!/bin/sh

NUM=`ls /usr/share/blanket/screensaver/bg_medium_ss*.png | wc -l`

RANDOM=`awk -v num=$NUM 'BEGIN { srand(); printf("%d\n",int(rand()*num)); }'`

if [[ $RANDOM -lt 10 ]]; then
  RANDOM="0$RANDOM"
fi

echo "ss$RANDOM" > /var/local/blanket/screensaver/last_ss
