.TH KINDLETOOL 1 11/09/12 Linux KindleTool
.SH NAME
KindleTool \- creates/extracts Kindle updates and more
.SH SYNOPSIS
.B kindletool
.RB < create | convert | extract | info | md | dm | version | help >
.RI [ options ]
.SH DESCRIPTION
KindleTool will help you, among other things, create, convert, mangle or extract Kindle update packages.
.SH OPTIONS
.SS create
.IR Syntax :
.RB < type "> <" devices "> [" options "] <" dir | file ">... [<" output ">]"
.RS
Creates a Kindle update package
.br
You should be able to throw a mix of files & directories as input without trouble.
.br
Just keep in mind that by default, if you feed it absolute paths, it will archive absolute paths, which usually isn't what you want!
.br
If input is a single tarball
.RI ( .tgz " or " .tar.gz )
file, we assume it is properly packaged (bundlefile & sigfile), and will only convert it to an update.
.br
Output should be a file with the extension
.IR .bin ,
if it is not provided, or if it's a single dash, output to stdout.
.br
In case of OTA updates, all files with the extension
.IR .ffs " or " .sh
will be treated as update scripts.
.RE
.TP
.RB < ota | ota2 | recovery | recovery2 >
Set the update type.
.br
.B OTA V1
update package. Works on Kindle 3 and older.
.br
.B OTA V2
signed update package. Works on Kindle 4 and newer.
.br
.B Recovery
package for restoring partitions.
.br
.B Recovery V2
Recovery V2 package for restoring partitions. Works on Kindle 5 (PaperWhite) and newer.
.TP
.BI \-d ", " \-\-device " device"
Set the target device(s).
.br
.BR "OTA V1" " and " Recovery
packages only support one device.
.br
.BR "OTA V2" " and " "Recovery V2"
packages can support multiple devices, this parameter can then be specified multiple times.
.br
.I device
is one of
.BR k1 ", " k2 ", " k2i ", " dx ", " dxi ", " dxg ", " k3w ", " k3g ", " k3gb ", " k4 ", " k4b ", " kindle4 ", " k5w ", " k5g ", " k5gb ", " k5u ", " pw ", " pwg ", " pwgb ", " kindle5 ", " touch ", " paperwhite " or " none
.TP
.BI \-p ", " \-\-platform " platform"
Set the target platform.
.br
.BR "Recovery FB02" " with " "header rev 2" " and " "Recovery V2" " only."
Use a single platform per package.
.br
.I platform
is one of
.BR mario ", " luigi ", " banjo ", " yoshi ", " yoshime-p " or " yoshime .
.TP
.BR \-k ", " \-\-key " file"
PEM file containing RSA private key to sign update. Default is popular jailbreak key.
.TP
.BR \-b ", " \-\-bundle " type"
Manually specify package magic number. Overrides the update type.
.br
.I type
is one of
.BR FB01 ", " FB02 " for "
.IR recovery ;
.BR FB03 " for "
.IR recovery2 ;
.BR FC02 ", " FD03 " for "
.IR ota " or "
.BR FC04 ", " FD04 ", " FL01 " for "
.I ota2
.TP
.BR \-s ", " \-\-srcrev " uint"
.B OTA
updates only. Source revision.
.B OTA V1
uses
.IR uint ,
.B OTA V2
uses
.IR ulong .
.br
Lowest version of device that package supports. Default is
.IR 0 .
.TP
.BR \-t ", " \-\-tgtrev " uint"
.BR OTA " and " "Recovery V2"
updates only. Target revision.
.B OTA V1
uses
.IR uint ,
.BR "OTA V2" " and " "Recovery V2"
uses
.IR ulong .
.br
Highest version of device that package supports. Default is
.I ulong/uint max
value.
.TP
.BR \-h ", " \-\-hdrrev " uint"
.BR "Recovery FB02" " and " "Recovery V2" " only."
Header Revision. Default is
.IR 0 .
.TP
.BR \-1 ", " \-\-magic1 " uint"
.B Recovery
updates only. Magic number 1. Default is
.IR 0 .
.TP
.BR \-2 ", " \-\-magic2 " uint"
.B Recovery
updates only. Magic number 2. Default is
.IR 0 .
.TP
.BR \-m ", " \-\-minor " uint"
.B Recovery
updates only. Minor number. Default is
.IR 0 .
.TP
.BR \-c ", " \-\-cert " ushort"
.B OTA V2
updates only. The number of the certificate to use (found in /etc/uks on device). Default is
.IR 0 .
.br
.BR 0 " = "
.IR pubdevkey01.pem ,
.BR 1 " = "
.IR pubprodkey01.pem ,
.BR 2 " = "
.I pubprodkey02.pem
.TP
.BR \-o ", " \-\-opt " uchar"
.B OTA V1
updates only. One byte optional data expressed as a number. Default is
.IR 0 .
.TP
.BR \-r ", " \-\-crit " uchar"
.B OTA V2
updates only. One byte optional data expressed as a number. Default is
.IR 0 .
.TP
.BR \-x ", " \-\-meta " str"
.B OTA V2
updates only. An optional string to add. This parameter can then be specified multiple times.
.br
Format of metastring must be:
.BR key = \fIvalue
.TP
.BR \-a ", " \-\-archive
Keep the intermediate archive.
.TP
.BR \-u ", " \-\-unsigned
Build an unsigned package.
.TP
.BR \-C ", " \-\-legacy
Emulate the behaviour of yifanlu's KindleTool regarding directories. By default, we behave like tar:
.br
every path passed on the commandline is stored as-is in the archive. This switch changes that, and store paths
.br
relative to the path passed on the commandline, like if we had chdir'ed into it.
.SS convert
.IR Syntax :
.RB [ options "] <" input >...
.RS
Converts a Kindle update package to a gzipped TAR file, and delete input.
.RE
.TP
.BR \-c ", " \-\-stdout
Write to standard output, keeping original files unchanged
.TP
.BR \-i ", " \-\-info
Just print the package information, no conversion done
.TP
.BR \-s ", " \-\-sig
.B OTA V2
updates only. Extract the package signature.
.TP
.BR \-k ", " \-\-keep
Don't delete the input package.
.TP
.BR \-u ", " \-\-unsigned
Assume input is an unsigned package
.TP
.BR \-w ", " \-\-unwrap
Just unwrap the package, if it's wrapped in an UpdateSignature header
.SS extract
.IR Syntax :
.RB < input "> <" output >
.RS
Extracts a Kindle update package to a directory
.RE
.SS info
.IR Syntax :
.RB < serialno >
.RS
Get the default root password
.br
Unless you changed your password manually, the first password shown will be the right one.
.br
(The Kindle defaults to DES hashed passwords, which are truncated to 8 characters.
.br
See
.BR crypt (3)
for more details.)
.br
If you're looking for the recovery MMC export password, that's the second one.
.RE
.SS md
.IR Syntax :
.RB [< input ">] [<" output >]
.RS
Obfuscates data using Amazon's update algorithm.
.br
If no input is provided, input from stdin
.br
If no output is provided, output to stdout
.RE
.SS dm
.IR Syntax :
.RB [< input ">] [<" output >]
.RS
Deobfuscates data using Amazon's update algorithm.
.br
If no input is provided, input from stdin
.br
If no output is provided, output to stdout
.RE
.SS version
Show some info about this KindleTool build
.SS help
Show the help screen
.SH BUGS
Kindle 4.0+ has a known bug that prevents some updates with meta-strings to run.
.br
Currently, even though OTA V2 supports updates that run on multiple devices,
.br
it is not possible to create an update package that will run on both the Kindle 4 (No Touch) and Kindle 5 (Kindle Touch)